spring:
  application:
    name: task
  datasource:
    url: jdbc:postgresql://localhost:5555/spring-postgres
    username: gleb
    password: password
  jpa:
    hibernate:
      ddl-create: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          auto: update
server:
  port: 8085
  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      time-to-live: 60000
kafka:
  bootstrap-servers: localhost:9092
  task-outbox-topic: task_outbox_topic